//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkladEntities : DbContext
    {
        static SkladEntities context;
        static public string CnS { get; set; }
        public static SkladEntities GetContext()
        {
            if (context == null)
                context = new SkladEntities();
            return context;
        }
        public static string ConnectionString()
        {
            return CnS;
        }
        public SkladEntities()
            : base("name=SkladEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<items> items { get; set; }
        public virtual DbSet<Кабели> Кабели { get; set; }
    }
}
