//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Кабели
    {
        public int group_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> Длина { get; set; }
        public string Порт1 { get; set; }
        public string Порт2 { get; set; }
    
        public virtual items items { get; set; }
    }
}
